### ISSUE TITLE
Theo_sol_exec_cj code

### ISSUE THREAD

**Issue by ghost** [othmaneM/RL_adap_stepsize#1]
Hey, It seems the code for Theo_sol_exec_cj is missing for the optimal execution example. I think it'd be helpful for replicating your study.

**Comment by otM23** [comment]
Thank you for your email and sorry for the late reply I was travelling. I
am going to check and add what is missing if needed.

**Comment by otM23** [comment]
Ok I 've just checked it and Theo_sol_exec_cj can be found in the folder RL_adap_stepsize/Opti_exec/Auxiliary/

**Comment by ghost** [comment]
Thanks
